### ISSUE TITLE
Executing `test_scl_usage` when tty exists waits on 'cat' forever

### ISSUE THREAD

**Issue by lukaszachy** [sclorg/s2i-php-container#387] opened 2022-11-04 07:42 UTC
From bash verbose when this test is executed:

```bash
[INFO] Testing the image SCL enable...

++ docker run --rm php-image /bin/bash -c ''
+ out=
+ echo ''
+ grep -q ''
+++ cat
```
and there it stops. When there is no tty cat exists immediately and test continues as expected.

**Comment by lukaszachy** [comment] 2022-11-04 10:06
It looks that it happens because `cid_file` variable is no longer defined.

**Comment by lukaszachy** [comment] 2022-12-12 09:43
@phracek Could you take a look please?

**Comment by phracek** [comment] 2023-01-02 14:54
This issue looks like a regression of https://github.com/sclorg/container-common-scripts/pull/306

**Comment by pkubatrh** [comment] 2023-01-27 08:53
This is still an issue with updated common scripts

**Comment by zmiklank** [comment] 2023-03-28 08:58
This is fixed by ed62e9a8d5b30ee6906ca7a3a5fd47d046f65952.

It did not make sense to call this test explicitly from testsuite, as it is used as a part of other tests.

If issue still persists please feel free to reopen.

**Closed by zmiklank** 2023-03-28 08:58 UTC
