### ISSUE TITLE
8.1 version of s2i-php-container web server user does not get the environment variables (env) secrets from Openshift

### ISSUE THREAD

**Issue by olstjos** [sclorg/s2i-php-container#402] opened 2023-03-15 22:23 UTC
Ok so I've tested 8.1, and have found the following:

Our secret environment variables are showing up for the pod user but the web server instance does not see our environment variables.

This crashes our application because our server cannot connect to the database.

So somewhere in the 8.1 recipe, the web server user is no longer the same user that gets the openshift secrets.

It's possible that I could maybe fix this on my end but I'm not sure where to start.

Our image is from here:
https://github.com/ised-ocp-prod/sclorg-s2i-php/tree/master/8.1

**Comment by pkubatrh** [comment] 2023-03-16 07:15
Duplicate of #403

**Closed by pkubatrh** 2023-03-16 07:15 UTC
